apiVersion: v1
kind: Pod
metadata:
  name: oom-trap
spec:
  containers:
  - name: memory-hog
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--timeout", "10s"]
    resources:
      limits:
        memory: "50Mi" # Will crash immediately