apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smoke-test-zombie
  labels:
    business/managed: "true"
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }
  storageClassName: local-path